blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/jfuginay/coursebuild.it/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/jfuginay/coursebuild.it/blob/main/README.md
    about: Read the project documentation and setup guides