#!/bin/bash

echo "🧪 Testing InfoBite Setup..."
echo ""
echo "1. First, make sure you've run the SQL migration in Supabase"
echo "2. Then run: node scripts/verify-infobite-setup.js"
echo ""
echo "To test locally:"
echo "1. npm run dev"
echo "2. Go to any course page"
echo "3. Log in as a user"
echo "4. You should see the autonomy slider"
echo "5. Set it to 'Guide Me' mode"
echo "6. Answer 2 questions wrong to trigger hints"
echo ""
echo "The InfoBite system will:"
echo "- Poll every 30 seconds while video is playing"
echo "- Show hints based on autonomy level"
echo "- Track wrong answer streaks"
echo "- Respect cooldown periods"